/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EnrolmentRouteImport } from './routes/_enrolment'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminErrorPreviewRouteImport } from './routes/admin/error-preview'
import { Route as AdminProtectedRouteImport } from './routes/admin/_protected'
import { Route as AdminPreviewRouteImport } from './routes/admin/_preview'
import { Route as EnrolmentTwoFactorSetupIndexRouteImport } from './routes/_enrolment/two-factor-setup/index'
import { Route as AuthLoginIndexRouteImport } from './routes/_auth/login/index'
import { Route as AdminProtectedTransactionsRouteRouteImport } from './routes/admin/_protected/transactions/route'
import { Route as AdminProtectedProductsRouteRouteImport } from './routes/admin/_protected/products/route'
import { Route as AdminProtectedContentRouteRouteImport } from './routes/admin/_protected/content/route'
import { Route as AdminProtectedCategoriesRouteRouteImport } from './routes/admin/_protected/categories/route'
import { Route as AdminPreviewProductsPreviewRouteRouteImport } from './routes/admin/_preview/products-preview/route'
import { Route as AdminPreviewCategoriesPreviewRouteRouteImport } from './routes/admin/_preview/categories-preview/route'
import { Route as AdminProtectedUsersIndexRouteImport } from './routes/admin/_protected/users/index'
import { Route as AdminProtectedTransactionsIndexRouteImport } from './routes/admin/_protected/transactions/index'
import { Route as AdminProtectedSettingsIndexRouteImport } from './routes/admin/_protected/settings/index'
import { Route as AdminProtectedReportsIndexRouteImport } from './routes/admin/_protected/reports/index'
import { Route as AdminProtectedRefundsIndexRouteImport } from './routes/admin/_protected/refunds/index'
import { Route as AdminProtectedPromosIndexRouteImport } from './routes/admin/_protected/promos/index'
import { Route as AdminProtectedProductsIndexRouteImport } from './routes/admin/_protected/products/index'
import { Route as AdminProtectedPricingIndexRouteImport } from './routes/admin/_protected/pricing/index'
import { Route as AdminProtectedPaymentsIndexRouteImport } from './routes/admin/_protected/payments/index'
import { Route as AdminProtectedNotificationsIndexRouteImport } from './routes/admin/_protected/notifications/index'
import { Route as AdminProtectedMembershipsIndexRouteImport } from './routes/admin/_protected/memberships/index'
import { Route as AdminProtectedIntegrationIndexRouteImport } from './routes/admin/_protected/integration/index'
import { Route as AdminProtectedFlashSalesIndexRouteImport } from './routes/admin/_protected/flash-sales/index'
import { Route as AdminProtectedFinancialIndexRouteImport } from './routes/admin/_protected/financial/index'
import { Route as AdminProtectedFeedbackIndexRouteImport } from './routes/admin/_protected/feedback/index'
import { Route as AdminProtectedDashboardIndexRouteImport } from './routes/admin/_protected/dashboard/index'
import { Route as AdminProtectedContentIndexRouteImport } from './routes/admin/_protected/content/index'
import { Route as AdminProtectedCategoriesIndexRouteImport } from './routes/admin/_protected/categories/index'
import { Route as AdminProtectedActivityIndexRouteImport } from './routes/admin/_protected/activity/index'
import { Route as AdminPreviewTransactionPreviewIndexRouteImport } from './routes/admin/_preview/transaction-preview/index'
import { Route as AdminPreviewRefundsPreviewIndexRouteImport } from './routes/admin/_preview/refunds-preview/index'
import { Route as AdminPreviewProductsPreviewIndexRouteImport } from './routes/admin/_preview/products-preview/index'
import { Route as AdminPreviewIntegrationPreviewIndexRouteImport } from './routes/admin/_preview/integration-preview/index'
import { Route as AdminPreviewFinancePreviewIndexRouteImport } from './routes/admin/_preview/finance-preview/index'
import { Route as AdminPreviewDashboardPreviewIndexRouteImport } from './routes/admin/_preview/dashboard-preview/index'
import { Route as AdminPreviewCategoriesPreviewIndexRouteImport } from './routes/admin/_preview/categories-preview/index'
import { Route as AdminProtectedUsersUserIdIndexRouteImport } from './routes/admin/_protected/users/$userId/index'
import { Route as AdminProtectedTransactionsManualIndexRouteImport } from './routes/admin/_protected/transactions/manual/index'
import { Route as AdminProtectedTransactionsAutomaticIndexRouteImport } from './routes/admin/_protected/transactions/automatic/index'
import { Route as AdminProtectedSettingsSecurityIndexRouteImport } from './routes/admin/_protected/settings/security/index'
import { Route as AdminProtectedProductsProviderIndexRouteImport } from './routes/admin/_protected/products/provider/index'
import { Route as AdminProtectedProductsPriceLogIndexRouteImport } from './routes/admin/_protected/products/price-log/index'
import { Route as AdminProtectedProductsMainIndexRouteImport } from './routes/admin/_protected/products/main/index'
import { Route as AdminProtectedContentTestimonialsIndexRouteImport } from './routes/admin/_protected/content/testimonials/index'
import { Route as AdminProtectedContentPagesIndexRouteImport } from './routes/admin/_protected/content/pages/index'
import { Route as AdminProtectedContentNewsIndexRouteImport } from './routes/admin/_protected/content/news/index'
import { Route as AdminProtectedContentFaqsIndexRouteImport } from './routes/admin/_protected/content/faqs/index'
import { Route as AdminProtectedContentCategoriesIndexRouteImport } from './routes/admin/_protected/content/categories/index'
import { Route as AdminProtectedContentBannersIndexRouteImport } from './routes/admin/_protected/content/banners/index'
import { Route as AdminProtectedContentArticlesIndexRouteImport } from './routes/admin/_protected/content/articles/index'
import { Route as AdminProtectedContentAnnouncementsIndexRouteImport } from './routes/admin/_protected/content/announcements/index'
import { Route as AdminProtectedCategoriesSubCategoryIndexRouteImport } from './routes/admin/_protected/categories/sub-category/index'
import { Route as AdminProtectedCategoriesCategoryIndexRouteImport } from './routes/admin/_protected/categories/category/index'
import { Route as AdminProtectedCategoriesCategoryTypeIndexRouteImport } from './routes/admin/_protected/categories/category-type/index'
import { Route as AdminProtectedCategoriesCategoryServerIndexRouteImport } from './routes/admin/_protected/categories/category-server/index'
import { Route as AdminProtectedCategoriesCategoryProviderIndexRouteImport } from './routes/admin/_protected/categories/category-provider/index'
import { Route as AdminPreviewProductsPreviewProviderIndexRouteImport } from './routes/admin/_preview/products-preview/provider/index'
import { Route as AdminPreviewProductsPreviewPriceLogIndexRouteImport } from './routes/admin/_preview/products-preview/price-log/index'
import { Route as AdminPreviewProductsPreviewMainIndexRouteImport } from './routes/admin/_preview/products-preview/main/index'
import { Route as AdminPreviewCategoriesPreviewSubCategoryIndexRouteImport } from './routes/admin/_preview/categories-preview/sub-category/index'
import { Route as AdminPreviewCategoriesPreviewCategoryIndexRouteImport } from './routes/admin/_preview/categories-preview/category/index'
import { Route as AdminPreviewCategoriesPreviewCategoryTypeIndexRouteImport } from './routes/admin/_preview/categories-preview/category-type/index'
import { Route as AdminPreviewCategoriesPreviewCategoryServerIndexRouteImport } from './routes/admin/_preview/categories-preview/category-server/index'
import { Route as AdminPreviewCategoriesPreviewCategoryProviderIndexRouteImport } from './routes/admin/_preview/categories-preview/category-provider/index'
import { Route as AdminProtectedProductsProviderSetProfitMarginIndexRouteImport } from './routes/admin/_protected/products/provider/set-profit-margin/index'
import { Route as AdminProtectedProductsProviderAddIndexRouteImport } from './routes/admin/_protected/products/provider/add/index'
import { Route as AdminProtectedProductsMainSetPriceLimitIndexRouteImport } from './routes/admin/_protected/products/main/set-price-limit/index'
import { Route as AdminProtectedProductsMainAddIndexRouteImport } from './routes/admin/_protected/products/main/add/index'
import { Route as AdminPreviewTransactionPreviewInvoiceNoEditIndexRouteImport } from './routes/admin/_preview/transaction-preview/$invoiceNo/edit/index'
import { Route as AdminPreviewProductsPreviewMainAddIndexRouteImport } from './routes/admin/_preview/products-preview/main/add/index'
import { Route as AdminProtectedTransactionsManualInvoiceNoEditIndexRouteImport } from './routes/admin/_protected/transactions/manual/$invoiceNo/edit/index'
import { Route as AdminProtectedTransactionsAutomaticInvoiceNoEditIndexRouteImport } from './routes/admin/_protected/transactions/automatic/$invoiceNo/edit/index'

const EnrolmentRoute = EnrolmentRouteImport.update({
  id: '/_enrolment',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminErrorPreviewRoute = AdminErrorPreviewRouteImport.update({
  id: '/admin/error-preview',
  path: '/admin/error-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProtectedRoute = AdminProtectedRouteImport.update({
  id: '/admin/_protected',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPreviewRoute = AdminPreviewRouteImport.update({
  id: '/admin/_preview',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const EnrolmentTwoFactorSetupIndexRoute =
  EnrolmentTwoFactorSetupIndexRouteImport.update({
    id: '/two-factor-setup/',
    path: '/two-factor-setup/',
    getParentRoute: () => EnrolmentRoute,
  } as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AdminProtectedTransactionsRouteRoute =
  AdminProtectedTransactionsRouteRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AdminProtectedRoute,
  } as any)
const AdminProtectedProductsRouteRoute =
  AdminProtectedProductsRouteRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AdminProtectedRoute,
  } as any)
const AdminProtectedContentRouteRoute =
  AdminProtectedContentRouteRouteImport.update({
    id: '/content',
    path: '/content',
    getParentRoute: () => AdminProtectedRoute,
  } as any)
const AdminProtectedCategoriesRouteRoute =
  AdminProtectedCategoriesRouteRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AdminProtectedRoute,
  } as any)
const AdminPreviewProductsPreviewRouteRoute =
  AdminPreviewProductsPreviewRouteRouteImport.update({
    id: '/products-preview',
    path: '/products-preview',
    getParentRoute: () => AdminPreviewRoute,
  } as any)
const AdminPreviewCategoriesPreviewRouteRoute =
  AdminPreviewCategoriesPreviewRouteRouteImport.update({
    id: '/categories-preview',
    path: '/categories-preview',
    getParentRoute: () => AdminPreviewRoute,
  } as any)
const AdminProtectedUsersIndexRoute =
  AdminProtectedUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AdminProtectedRoute,
  } as any)
const AdminProtectedTransactionsIndexRoute =
  AdminProtectedTransactionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminProtectedTransactionsRouteRoute,
  } as any)
const AdminProtectedSettingsIndexRoute =
  AdminProtectedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AdminProtectedRoute,
  } as any)
const AdminProtectedReportsIndexRoute =
  AdminProtectedReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => AdminProtectedRoute,
  } as any)
const AdminProtectedRefundsIndexRoute =
  AdminProtectedRefundsIndexRouteImport.update({
    id: '/refunds/',
    path: '/refunds/',
    getParentRoute: () => AdminProtectedRoute,
  } as any)
const AdminProtectedPromosIndexRoute =
  AdminProtectedPromosIndexRouteImport.update({
    id: '/promos/',
    path: '/promos/',
    getParentRoute: () => AdminProtectedRoute,
  } as any)
const AdminProtectedProductsIndexRoute =
  AdminProtectedProductsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminProtectedProductsRouteRoute,
  } as any)
const AdminProtectedPricingIndexRoute =
  AdminProtectedPricingIndexRouteImport.update({
    id: '/pricing/',
    path: '/pricing/',
    getParentRoute: () => AdminProtectedRoute,
  } as any)
const AdminProtectedPaymentsIndexRoute =
  AdminProtectedPaymentsIndexRouteImport.update({
    id: '/payments/',
    path: '/payments/',
    getParentRoute: () => AdminProtectedRoute,
  } as any)
const AdminProtectedNotificationsIndexRoute =
  AdminProtectedNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => AdminProtectedRoute,
  } as any)
const AdminProtectedMembershipsIndexRoute =
  AdminProtectedMembershipsIndexRouteImport.update({
    id: '/memberships/',
    path: '/memberships/',
    getParentRoute: () => AdminProtectedRoute,
  } as any)
const AdminProtectedIntegrationIndexRoute =
  AdminProtectedIntegrationIndexRouteImport.update({
    id: '/integration/',
    path: '/integration/',
    getParentRoute: () => AdminProtectedRoute,
  } as any)
const AdminProtectedFlashSalesIndexRoute =
  AdminProtectedFlashSalesIndexRouteImport.update({
    id: '/flash-sales/',
    path: '/flash-sales/',
    getParentRoute: () => AdminProtectedRoute,
  } as any)
const AdminProtectedFinancialIndexRoute =
  AdminProtectedFinancialIndexRouteImport.update({
    id: '/financial/',
    path: '/financial/',
    getParentRoute: () => AdminProtectedRoute,
  } as any)
const AdminProtectedFeedbackIndexRoute =
  AdminProtectedFeedbackIndexRouteImport.update({
    id: '/feedback/',
    path: '/feedback/',
    getParentRoute: () => AdminProtectedRoute,
  } as any)
const AdminProtectedDashboardIndexRoute =
  AdminProtectedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AdminProtectedRoute,
  } as any)
const AdminProtectedContentIndexRoute =
  AdminProtectedContentIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminProtectedContentRouteRoute,
  } as any)
const AdminProtectedCategoriesIndexRoute =
  AdminProtectedCategoriesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminProtectedCategoriesRouteRoute,
  } as any)
const AdminProtectedActivityIndexRoute =
  AdminProtectedActivityIndexRouteImport.update({
    id: '/activity/',
    path: '/activity/',
    getParentRoute: () => AdminProtectedRoute,
  } as any)
const AdminPreviewTransactionPreviewIndexRoute =
  AdminPreviewTransactionPreviewIndexRouteImport.update({
    id: '/transaction-preview/',
    path: '/transaction-preview/',
    getParentRoute: () => AdminPreviewRoute,
  } as any)
const AdminPreviewRefundsPreviewIndexRoute =
  AdminPreviewRefundsPreviewIndexRouteImport.update({
    id: '/refunds-preview/',
    path: '/refunds-preview/',
    getParentRoute: () => AdminPreviewRoute,
  } as any)
const AdminPreviewProductsPreviewIndexRoute =
  AdminPreviewProductsPreviewIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminPreviewProductsPreviewRouteRoute,
  } as any)
const AdminPreviewIntegrationPreviewIndexRoute =
  AdminPreviewIntegrationPreviewIndexRouteImport.update({
    id: '/integration-preview/',
    path: '/integration-preview/',
    getParentRoute: () => AdminPreviewRoute,
  } as any)
const AdminPreviewFinancePreviewIndexRoute =
  AdminPreviewFinancePreviewIndexRouteImport.update({
    id: '/finance-preview/',
    path: '/finance-preview/',
    getParentRoute: () => AdminPreviewRoute,
  } as any)
const AdminPreviewDashboardPreviewIndexRoute =
  AdminPreviewDashboardPreviewIndexRouteImport.update({
    id: '/dashboard-preview/',
    path: '/dashboard-preview/',
    getParentRoute: () => AdminPreviewRoute,
  } as any)
const AdminPreviewCategoriesPreviewIndexRoute =
  AdminPreviewCategoriesPreviewIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminPreviewCategoriesPreviewRouteRoute,
  } as any)
const AdminProtectedUsersUserIdIndexRoute =
  AdminProtectedUsersUserIdIndexRouteImport.update({
    id: '/users/$userId/',
    path: '/users/$userId/',
    getParentRoute: () => AdminProtectedRoute,
  } as any)
const AdminProtectedTransactionsManualIndexRoute =
  AdminProtectedTransactionsManualIndexRouteImport.update({
    id: '/manual/',
    path: '/manual/',
    getParentRoute: () => AdminProtectedTransactionsRouteRoute,
  } as any)
const AdminProtectedTransactionsAutomaticIndexRoute =
  AdminProtectedTransactionsAutomaticIndexRouteImport.update({
    id: '/automatic/',
    path: '/automatic/',
    getParentRoute: () => AdminProtectedTransactionsRouteRoute,
  } as any)
const AdminProtectedSettingsSecurityIndexRoute =
  AdminProtectedSettingsSecurityIndexRouteImport.update({
    id: '/settings/security/',
    path: '/settings/security/',
    getParentRoute: () => AdminProtectedRoute,
  } as any)
const AdminProtectedProductsProviderIndexRoute =
  AdminProtectedProductsProviderIndexRouteImport.update({
    id: '/provider/',
    path: '/provider/',
    getParentRoute: () => AdminProtectedProductsRouteRoute,
  } as any)
const AdminProtectedProductsPriceLogIndexRoute =
  AdminProtectedProductsPriceLogIndexRouteImport.update({
    id: '/price-log/',
    path: '/price-log/',
    getParentRoute: () => AdminProtectedProductsRouteRoute,
  } as any)
const AdminProtectedProductsMainIndexRoute =
  AdminProtectedProductsMainIndexRouteImport.update({
    id: '/main/',
    path: '/main/',
    getParentRoute: () => AdminProtectedProductsRouteRoute,
  } as any)
const AdminProtectedContentTestimonialsIndexRoute =
  AdminProtectedContentTestimonialsIndexRouteImport.update({
    id: '/testimonials/',
    path: '/testimonials/',
    getParentRoute: () => AdminProtectedContentRouteRoute,
  } as any)
const AdminProtectedContentPagesIndexRoute =
  AdminProtectedContentPagesIndexRouteImport.update({
    id: '/pages/',
    path: '/pages/',
    getParentRoute: () => AdminProtectedContentRouteRoute,
  } as any)
const AdminProtectedContentNewsIndexRoute =
  AdminProtectedContentNewsIndexRouteImport.update({
    id: '/news/',
    path: '/news/',
    getParentRoute: () => AdminProtectedContentRouteRoute,
  } as any)
const AdminProtectedContentFaqsIndexRoute =
  AdminProtectedContentFaqsIndexRouteImport.update({
    id: '/faqs/',
    path: '/faqs/',
    getParentRoute: () => AdminProtectedContentRouteRoute,
  } as any)
const AdminProtectedContentCategoriesIndexRoute =
  AdminProtectedContentCategoriesIndexRouteImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => AdminProtectedContentRouteRoute,
  } as any)
const AdminProtectedContentBannersIndexRoute =
  AdminProtectedContentBannersIndexRouteImport.update({
    id: '/banners/',
    path: '/banners/',
    getParentRoute: () => AdminProtectedContentRouteRoute,
  } as any)
const AdminProtectedContentArticlesIndexRoute =
  AdminProtectedContentArticlesIndexRouteImport.update({
    id: '/articles/',
    path: '/articles/',
    getParentRoute: () => AdminProtectedContentRouteRoute,
  } as any)
const AdminProtectedContentAnnouncementsIndexRoute =
  AdminProtectedContentAnnouncementsIndexRouteImport.update({
    id: '/announcements/',
    path: '/announcements/',
    getParentRoute: () => AdminProtectedContentRouteRoute,
  } as any)
const AdminProtectedCategoriesSubCategoryIndexRoute =
  AdminProtectedCategoriesSubCategoryIndexRouteImport.update({
    id: '/sub-category/',
    path: '/sub-category/',
    getParentRoute: () => AdminProtectedCategoriesRouteRoute,
  } as any)
const AdminProtectedCategoriesCategoryIndexRoute =
  AdminProtectedCategoriesCategoryIndexRouteImport.update({
    id: '/category/',
    path: '/category/',
    getParentRoute: () => AdminProtectedCategoriesRouteRoute,
  } as any)
const AdminProtectedCategoriesCategoryTypeIndexRoute =
  AdminProtectedCategoriesCategoryTypeIndexRouteImport.update({
    id: '/category-type/',
    path: '/category-type/',
    getParentRoute: () => AdminProtectedCategoriesRouteRoute,
  } as any)
const AdminProtectedCategoriesCategoryServerIndexRoute =
  AdminProtectedCategoriesCategoryServerIndexRouteImport.update({
    id: '/category-server/',
    path: '/category-server/',
    getParentRoute: () => AdminProtectedCategoriesRouteRoute,
  } as any)
const AdminProtectedCategoriesCategoryProviderIndexRoute =
  AdminProtectedCategoriesCategoryProviderIndexRouteImport.update({
    id: '/category-provider/',
    path: '/category-provider/',
    getParentRoute: () => AdminProtectedCategoriesRouteRoute,
  } as any)
const AdminPreviewProductsPreviewProviderIndexRoute =
  AdminPreviewProductsPreviewProviderIndexRouteImport.update({
    id: '/provider/',
    path: '/provider/',
    getParentRoute: () => AdminPreviewProductsPreviewRouteRoute,
  } as any)
const AdminPreviewProductsPreviewPriceLogIndexRoute =
  AdminPreviewProductsPreviewPriceLogIndexRouteImport.update({
    id: '/price-log/',
    path: '/price-log/',
    getParentRoute: () => AdminPreviewProductsPreviewRouteRoute,
  } as any)
const AdminPreviewProductsPreviewMainIndexRoute =
  AdminPreviewProductsPreviewMainIndexRouteImport.update({
    id: '/main/',
    path: '/main/',
    getParentRoute: () => AdminPreviewProductsPreviewRouteRoute,
  } as any)
const AdminPreviewCategoriesPreviewSubCategoryIndexRoute =
  AdminPreviewCategoriesPreviewSubCategoryIndexRouteImport.update({
    id: '/sub-category/',
    path: '/sub-category/',
    getParentRoute: () => AdminPreviewCategoriesPreviewRouteRoute,
  } as any)
const AdminPreviewCategoriesPreviewCategoryIndexRoute =
  AdminPreviewCategoriesPreviewCategoryIndexRouteImport.update({
    id: '/category/',
    path: '/category/',
    getParentRoute: () => AdminPreviewCategoriesPreviewRouteRoute,
  } as any)
const AdminPreviewCategoriesPreviewCategoryTypeIndexRoute =
  AdminPreviewCategoriesPreviewCategoryTypeIndexRouteImport.update({
    id: '/category-type/',
    path: '/category-type/',
    getParentRoute: () => AdminPreviewCategoriesPreviewRouteRoute,
  } as any)
const AdminPreviewCategoriesPreviewCategoryServerIndexRoute =
  AdminPreviewCategoriesPreviewCategoryServerIndexRouteImport.update({
    id: '/category-server/',
    path: '/category-server/',
    getParentRoute: () => AdminPreviewCategoriesPreviewRouteRoute,
  } as any)
const AdminPreviewCategoriesPreviewCategoryProviderIndexRoute =
  AdminPreviewCategoriesPreviewCategoryProviderIndexRouteImport.update({
    id: '/category-provider/',
    path: '/category-provider/',
    getParentRoute: () => AdminPreviewCategoriesPreviewRouteRoute,
  } as any)
const AdminProtectedProductsProviderSetProfitMarginIndexRoute =
  AdminProtectedProductsProviderSetProfitMarginIndexRouteImport.update({
    id: '/provider/set-profit-margin/',
    path: '/provider/set-profit-margin/',
    getParentRoute: () => AdminProtectedProductsRouteRoute,
  } as any)
const AdminProtectedProductsProviderAddIndexRoute =
  AdminProtectedProductsProviderAddIndexRouteImport.update({
    id: '/provider/add/',
    path: '/provider/add/',
    getParentRoute: () => AdminProtectedProductsRouteRoute,
  } as any)
const AdminProtectedProductsMainSetPriceLimitIndexRoute =
  AdminProtectedProductsMainSetPriceLimitIndexRouteImport.update({
    id: '/main/set-price-limit/',
    path: '/main/set-price-limit/',
    getParentRoute: () => AdminProtectedProductsRouteRoute,
  } as any)
const AdminProtectedProductsMainAddIndexRoute =
  AdminProtectedProductsMainAddIndexRouteImport.update({
    id: '/main/add/',
    path: '/main/add/',
    getParentRoute: () => AdminProtectedProductsRouteRoute,
  } as any)
const AdminPreviewTransactionPreviewInvoiceNoEditIndexRoute =
  AdminPreviewTransactionPreviewInvoiceNoEditIndexRouteImport.update({
    id: '/transaction-preview/$invoiceNo/edit/',
    path: '/transaction-preview/$invoiceNo/edit/',
    getParentRoute: () => AdminPreviewRoute,
  } as any)
const AdminPreviewProductsPreviewMainAddIndexRoute =
  AdminPreviewProductsPreviewMainAddIndexRouteImport.update({
    id: '/main/add/',
    path: '/main/add/',
    getParentRoute: () => AdminPreviewProductsPreviewRouteRoute,
  } as any)
const AdminProtectedTransactionsManualInvoiceNoEditIndexRoute =
  AdminProtectedTransactionsManualInvoiceNoEditIndexRouteImport.update({
    id: '/manual/$invoiceNo/edit/',
    path: '/manual/$invoiceNo/edit/',
    getParentRoute: () => AdminProtectedTransactionsRouteRoute,
  } as any)
const AdminProtectedTransactionsAutomaticInvoiceNoEditIndexRoute =
  AdminProtectedTransactionsAutomaticInvoiceNoEditIndexRouteImport.update({
    id: '/automatic/$invoiceNo/edit/',
    path: '/automatic/$invoiceNo/edit/',
    getParentRoute: () => AdminProtectedTransactionsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminProtectedRouteWithChildren
  '/admin/error-preview': typeof AdminErrorPreviewRoute
  '/admin/categories-preview': typeof AdminPreviewCategoriesPreviewRouteRouteWithChildren
  '/admin/products-preview': typeof AdminPreviewProductsPreviewRouteRouteWithChildren
  '/admin/categories': typeof AdminProtectedCategoriesRouteRouteWithChildren
  '/admin/content': typeof AdminProtectedContentRouteRouteWithChildren
  '/admin/products': typeof AdminProtectedProductsRouteRouteWithChildren
  '/admin/transactions': typeof AdminProtectedTransactionsRouteRouteWithChildren
  '/login/': typeof AuthLoginIndexRoute
  '/two-factor-setup/': typeof EnrolmentTwoFactorSetupIndexRoute
  '/admin/categories-preview/': typeof AdminPreviewCategoriesPreviewIndexRoute
  '/admin/dashboard-preview/': typeof AdminPreviewDashboardPreviewIndexRoute
  '/admin/finance-preview/': typeof AdminPreviewFinancePreviewIndexRoute
  '/admin/integration-preview/': typeof AdminPreviewIntegrationPreviewIndexRoute
  '/admin/products-preview/': typeof AdminPreviewProductsPreviewIndexRoute
  '/admin/refunds-preview/': typeof AdminPreviewRefundsPreviewIndexRoute
  '/admin/transaction-preview/': typeof AdminPreviewTransactionPreviewIndexRoute
  '/admin/activity/': typeof AdminProtectedActivityIndexRoute
  '/admin/categories/': typeof AdminProtectedCategoriesIndexRoute
  '/admin/content/': typeof AdminProtectedContentIndexRoute
  '/admin/dashboard/': typeof AdminProtectedDashboardIndexRoute
  '/admin/feedback/': typeof AdminProtectedFeedbackIndexRoute
  '/admin/financial/': typeof AdminProtectedFinancialIndexRoute
  '/admin/flash-sales/': typeof AdminProtectedFlashSalesIndexRoute
  '/admin/integration/': typeof AdminProtectedIntegrationIndexRoute
  '/admin/memberships/': typeof AdminProtectedMembershipsIndexRoute
  '/admin/notifications/': typeof AdminProtectedNotificationsIndexRoute
  '/admin/payments/': typeof AdminProtectedPaymentsIndexRoute
  '/admin/pricing/': typeof AdminProtectedPricingIndexRoute
  '/admin/products/': typeof AdminProtectedProductsIndexRoute
  '/admin/promos/': typeof AdminProtectedPromosIndexRoute
  '/admin/refunds/': typeof AdminProtectedRefundsIndexRoute
  '/admin/reports/': typeof AdminProtectedReportsIndexRoute
  '/admin/settings/': typeof AdminProtectedSettingsIndexRoute
  '/admin/transactions/': typeof AdminProtectedTransactionsIndexRoute
  '/admin/users/': typeof AdminProtectedUsersIndexRoute
  '/admin/categories-preview/category-provider/': typeof AdminPreviewCategoriesPreviewCategoryProviderIndexRoute
  '/admin/categories-preview/category-server/': typeof AdminPreviewCategoriesPreviewCategoryServerIndexRoute
  '/admin/categories-preview/category-type/': typeof AdminPreviewCategoriesPreviewCategoryTypeIndexRoute
  '/admin/categories-preview/category/': typeof AdminPreviewCategoriesPreviewCategoryIndexRoute
  '/admin/categories-preview/sub-category/': typeof AdminPreviewCategoriesPreviewSubCategoryIndexRoute
  '/admin/products-preview/main/': typeof AdminPreviewProductsPreviewMainIndexRoute
  '/admin/products-preview/price-log/': typeof AdminPreviewProductsPreviewPriceLogIndexRoute
  '/admin/products-preview/provider/': typeof AdminPreviewProductsPreviewProviderIndexRoute
  '/admin/categories/category-provider/': typeof AdminProtectedCategoriesCategoryProviderIndexRoute
  '/admin/categories/category-server/': typeof AdminProtectedCategoriesCategoryServerIndexRoute
  '/admin/categories/category-type/': typeof AdminProtectedCategoriesCategoryTypeIndexRoute
  '/admin/categories/category/': typeof AdminProtectedCategoriesCategoryIndexRoute
  '/admin/categories/sub-category/': typeof AdminProtectedCategoriesSubCategoryIndexRoute
  '/admin/content/announcements/': typeof AdminProtectedContentAnnouncementsIndexRoute
  '/admin/content/articles/': typeof AdminProtectedContentArticlesIndexRoute
  '/admin/content/banners/': typeof AdminProtectedContentBannersIndexRoute
  '/admin/content/categories/': typeof AdminProtectedContentCategoriesIndexRoute
  '/admin/content/faqs/': typeof AdminProtectedContentFaqsIndexRoute
  '/admin/content/news/': typeof AdminProtectedContentNewsIndexRoute
  '/admin/content/pages/': typeof AdminProtectedContentPagesIndexRoute
  '/admin/content/testimonials/': typeof AdminProtectedContentTestimonialsIndexRoute
  '/admin/products/main/': typeof AdminProtectedProductsMainIndexRoute
  '/admin/products/price-log/': typeof AdminProtectedProductsPriceLogIndexRoute
  '/admin/products/provider/': typeof AdminProtectedProductsProviderIndexRoute
  '/admin/settings/security/': typeof AdminProtectedSettingsSecurityIndexRoute
  '/admin/transactions/automatic/': typeof AdminProtectedTransactionsAutomaticIndexRoute
  '/admin/transactions/manual/': typeof AdminProtectedTransactionsManualIndexRoute
  '/admin/users/$userId/': typeof AdminProtectedUsersUserIdIndexRoute
  '/admin/products-preview/main/add/': typeof AdminPreviewProductsPreviewMainAddIndexRoute
  '/admin/transaction-preview/$invoiceNo/edit/': typeof AdminPreviewTransactionPreviewInvoiceNoEditIndexRoute
  '/admin/products/main/add/': typeof AdminProtectedProductsMainAddIndexRoute
  '/admin/products/main/set-price-limit/': typeof AdminProtectedProductsMainSetPriceLimitIndexRoute
  '/admin/products/provider/add/': typeof AdminProtectedProductsProviderAddIndexRoute
  '/admin/products/provider/set-profit-margin/': typeof AdminProtectedProductsProviderSetProfitMarginIndexRoute
  '/admin/transactions/automatic/$invoiceNo/edit/': typeof AdminProtectedTransactionsAutomaticInvoiceNoEditIndexRoute
  '/admin/transactions/manual/$invoiceNo/edit/': typeof AdminProtectedTransactionsManualInvoiceNoEditIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminProtectedRouteWithChildren
  '/admin/error-preview': typeof AdminErrorPreviewRoute
  '/login': typeof AuthLoginIndexRoute
  '/two-factor-setup': typeof EnrolmentTwoFactorSetupIndexRoute
  '/admin/categories-preview': typeof AdminPreviewCategoriesPreviewIndexRoute
  '/admin/dashboard-preview': typeof AdminPreviewDashboardPreviewIndexRoute
  '/admin/finance-preview': typeof AdminPreviewFinancePreviewIndexRoute
  '/admin/integration-preview': typeof AdminPreviewIntegrationPreviewIndexRoute
  '/admin/products-preview': typeof AdminPreviewProductsPreviewIndexRoute
  '/admin/refunds-preview': typeof AdminPreviewRefundsPreviewIndexRoute
  '/admin/transaction-preview': typeof AdminPreviewTransactionPreviewIndexRoute
  '/admin/activity': typeof AdminProtectedActivityIndexRoute
  '/admin/categories': typeof AdminProtectedCategoriesIndexRoute
  '/admin/content': typeof AdminProtectedContentIndexRoute
  '/admin/dashboard': typeof AdminProtectedDashboardIndexRoute
  '/admin/feedback': typeof AdminProtectedFeedbackIndexRoute
  '/admin/financial': typeof AdminProtectedFinancialIndexRoute
  '/admin/flash-sales': typeof AdminProtectedFlashSalesIndexRoute
  '/admin/integration': typeof AdminProtectedIntegrationIndexRoute
  '/admin/memberships': typeof AdminProtectedMembershipsIndexRoute
  '/admin/notifications': typeof AdminProtectedNotificationsIndexRoute
  '/admin/payments': typeof AdminProtectedPaymentsIndexRoute
  '/admin/pricing': typeof AdminProtectedPricingIndexRoute
  '/admin/products': typeof AdminProtectedProductsIndexRoute
  '/admin/promos': typeof AdminProtectedPromosIndexRoute
  '/admin/refunds': typeof AdminProtectedRefundsIndexRoute
  '/admin/reports': typeof AdminProtectedReportsIndexRoute
  '/admin/settings': typeof AdminProtectedSettingsIndexRoute
  '/admin/transactions': typeof AdminProtectedTransactionsIndexRoute
  '/admin/users': typeof AdminProtectedUsersIndexRoute
  '/admin/categories-preview/category-provider': typeof AdminPreviewCategoriesPreviewCategoryProviderIndexRoute
  '/admin/categories-preview/category-server': typeof AdminPreviewCategoriesPreviewCategoryServerIndexRoute
  '/admin/categories-preview/category-type': typeof AdminPreviewCategoriesPreviewCategoryTypeIndexRoute
  '/admin/categories-preview/category': typeof AdminPreviewCategoriesPreviewCategoryIndexRoute
  '/admin/categories-preview/sub-category': typeof AdminPreviewCategoriesPreviewSubCategoryIndexRoute
  '/admin/products-preview/main': typeof AdminPreviewProductsPreviewMainIndexRoute
  '/admin/products-preview/price-log': typeof AdminPreviewProductsPreviewPriceLogIndexRoute
  '/admin/products-preview/provider': typeof AdminPreviewProductsPreviewProviderIndexRoute
  '/admin/categories/category-provider': typeof AdminProtectedCategoriesCategoryProviderIndexRoute
  '/admin/categories/category-server': typeof AdminProtectedCategoriesCategoryServerIndexRoute
  '/admin/categories/category-type': typeof AdminProtectedCategoriesCategoryTypeIndexRoute
  '/admin/categories/category': typeof AdminProtectedCategoriesCategoryIndexRoute
  '/admin/categories/sub-category': typeof AdminProtectedCategoriesSubCategoryIndexRoute
  '/admin/content/announcements': typeof AdminProtectedContentAnnouncementsIndexRoute
  '/admin/content/articles': typeof AdminProtectedContentArticlesIndexRoute
  '/admin/content/banners': typeof AdminProtectedContentBannersIndexRoute
  '/admin/content/categories': typeof AdminProtectedContentCategoriesIndexRoute
  '/admin/content/faqs': typeof AdminProtectedContentFaqsIndexRoute
  '/admin/content/news': typeof AdminProtectedContentNewsIndexRoute
  '/admin/content/pages': typeof AdminProtectedContentPagesIndexRoute
  '/admin/content/testimonials': typeof AdminProtectedContentTestimonialsIndexRoute
  '/admin/products/main': typeof AdminProtectedProductsMainIndexRoute
  '/admin/products/price-log': typeof AdminProtectedProductsPriceLogIndexRoute
  '/admin/products/provider': typeof AdminProtectedProductsProviderIndexRoute
  '/admin/settings/security': typeof AdminProtectedSettingsSecurityIndexRoute
  '/admin/transactions/automatic': typeof AdminProtectedTransactionsAutomaticIndexRoute
  '/admin/transactions/manual': typeof AdminProtectedTransactionsManualIndexRoute
  '/admin/users/$userId': typeof AdminProtectedUsersUserIdIndexRoute
  '/admin/products-preview/main/add': typeof AdminPreviewProductsPreviewMainAddIndexRoute
  '/admin/transaction-preview/$invoiceNo/edit': typeof AdminPreviewTransactionPreviewInvoiceNoEditIndexRoute
  '/admin/products/main/add': typeof AdminProtectedProductsMainAddIndexRoute
  '/admin/products/main/set-price-limit': typeof AdminProtectedProductsMainSetPriceLimitIndexRoute
  '/admin/products/provider/add': typeof AdminProtectedProductsProviderAddIndexRoute
  '/admin/products/provider/set-profit-margin': typeof AdminProtectedProductsProviderSetProfitMarginIndexRoute
  '/admin/transactions/automatic/$invoiceNo/edit': typeof AdminProtectedTransactionsAutomaticInvoiceNoEditIndexRoute
  '/admin/transactions/manual/$invoiceNo/edit': typeof AdminProtectedTransactionsManualInvoiceNoEditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_enrolment': typeof EnrolmentRouteWithChildren
  '/admin/_preview': typeof AdminPreviewRouteWithChildren
  '/admin/_protected': typeof AdminProtectedRouteWithChildren
  '/admin/error-preview': typeof AdminErrorPreviewRoute
  '/admin/_preview/categories-preview': typeof AdminPreviewCategoriesPreviewRouteRouteWithChildren
  '/admin/_preview/products-preview': typeof AdminPreviewProductsPreviewRouteRouteWithChildren
  '/admin/_protected/categories': typeof AdminProtectedCategoriesRouteRouteWithChildren
  '/admin/_protected/content': typeof AdminProtectedContentRouteRouteWithChildren
  '/admin/_protected/products': typeof AdminProtectedProductsRouteRouteWithChildren
  '/admin/_protected/transactions': typeof AdminProtectedTransactionsRouteRouteWithChildren
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/_enrolment/two-factor-setup/': typeof EnrolmentTwoFactorSetupIndexRoute
  '/admin/_preview/categories-preview/': typeof AdminPreviewCategoriesPreviewIndexRoute
  '/admin/_preview/dashboard-preview/': typeof AdminPreviewDashboardPreviewIndexRoute
  '/admin/_preview/finance-preview/': typeof AdminPreviewFinancePreviewIndexRoute
  '/admin/_preview/integration-preview/': typeof AdminPreviewIntegrationPreviewIndexRoute
  '/admin/_preview/products-preview/': typeof AdminPreviewProductsPreviewIndexRoute
  '/admin/_preview/refunds-preview/': typeof AdminPreviewRefundsPreviewIndexRoute
  '/admin/_preview/transaction-preview/': typeof AdminPreviewTransactionPreviewIndexRoute
  '/admin/_protected/activity/': typeof AdminProtectedActivityIndexRoute
  '/admin/_protected/categories/': typeof AdminProtectedCategoriesIndexRoute
  '/admin/_protected/content/': typeof AdminProtectedContentIndexRoute
  '/admin/_protected/dashboard/': typeof AdminProtectedDashboardIndexRoute
  '/admin/_protected/feedback/': typeof AdminProtectedFeedbackIndexRoute
  '/admin/_protected/financial/': typeof AdminProtectedFinancialIndexRoute
  '/admin/_protected/flash-sales/': typeof AdminProtectedFlashSalesIndexRoute
  '/admin/_protected/integration/': typeof AdminProtectedIntegrationIndexRoute
  '/admin/_protected/memberships/': typeof AdminProtectedMembershipsIndexRoute
  '/admin/_protected/notifications/': typeof AdminProtectedNotificationsIndexRoute
  '/admin/_protected/payments/': typeof AdminProtectedPaymentsIndexRoute
  '/admin/_protected/pricing/': typeof AdminProtectedPricingIndexRoute
  '/admin/_protected/products/': typeof AdminProtectedProductsIndexRoute
  '/admin/_protected/promos/': typeof AdminProtectedPromosIndexRoute
  '/admin/_protected/refunds/': typeof AdminProtectedRefundsIndexRoute
  '/admin/_protected/reports/': typeof AdminProtectedReportsIndexRoute
  '/admin/_protected/settings/': typeof AdminProtectedSettingsIndexRoute
  '/admin/_protected/transactions/': typeof AdminProtectedTransactionsIndexRoute
  '/admin/_protected/users/': typeof AdminProtectedUsersIndexRoute
  '/admin/_preview/categories-preview/category-provider/': typeof AdminPreviewCategoriesPreviewCategoryProviderIndexRoute
  '/admin/_preview/categories-preview/category-server/': typeof AdminPreviewCategoriesPreviewCategoryServerIndexRoute
  '/admin/_preview/categories-preview/category-type/': typeof AdminPreviewCategoriesPreviewCategoryTypeIndexRoute
  '/admin/_preview/categories-preview/category/': typeof AdminPreviewCategoriesPreviewCategoryIndexRoute
  '/admin/_preview/categories-preview/sub-category/': typeof AdminPreviewCategoriesPreviewSubCategoryIndexRoute
  '/admin/_preview/products-preview/main/': typeof AdminPreviewProductsPreviewMainIndexRoute
  '/admin/_preview/products-preview/price-log/': typeof AdminPreviewProductsPreviewPriceLogIndexRoute
  '/admin/_preview/products-preview/provider/': typeof AdminPreviewProductsPreviewProviderIndexRoute
  '/admin/_protected/categories/category-provider/': typeof AdminProtectedCategoriesCategoryProviderIndexRoute
  '/admin/_protected/categories/category-server/': typeof AdminProtectedCategoriesCategoryServerIndexRoute
  '/admin/_protected/categories/category-type/': typeof AdminProtectedCategoriesCategoryTypeIndexRoute
  '/admin/_protected/categories/category/': typeof AdminProtectedCategoriesCategoryIndexRoute
  '/admin/_protected/categories/sub-category/': typeof AdminProtectedCategoriesSubCategoryIndexRoute
  '/admin/_protected/content/announcements/': typeof AdminProtectedContentAnnouncementsIndexRoute
  '/admin/_protected/content/articles/': typeof AdminProtectedContentArticlesIndexRoute
  '/admin/_protected/content/banners/': typeof AdminProtectedContentBannersIndexRoute
  '/admin/_protected/content/categories/': typeof AdminProtectedContentCategoriesIndexRoute
  '/admin/_protected/content/faqs/': typeof AdminProtectedContentFaqsIndexRoute
  '/admin/_protected/content/news/': typeof AdminProtectedContentNewsIndexRoute
  '/admin/_protected/content/pages/': typeof AdminProtectedContentPagesIndexRoute
  '/admin/_protected/content/testimonials/': typeof AdminProtectedContentTestimonialsIndexRoute
  '/admin/_protected/products/main/': typeof AdminProtectedProductsMainIndexRoute
  '/admin/_protected/products/price-log/': typeof AdminProtectedProductsPriceLogIndexRoute
  '/admin/_protected/products/provider/': typeof AdminProtectedProductsProviderIndexRoute
  '/admin/_protected/settings/security/': typeof AdminProtectedSettingsSecurityIndexRoute
  '/admin/_protected/transactions/automatic/': typeof AdminProtectedTransactionsAutomaticIndexRoute
  '/admin/_protected/transactions/manual/': typeof AdminProtectedTransactionsManualIndexRoute
  '/admin/_protected/users/$userId/': typeof AdminProtectedUsersUserIdIndexRoute
  '/admin/_preview/products-preview/main/add/': typeof AdminPreviewProductsPreviewMainAddIndexRoute
  '/admin/_preview/transaction-preview/$invoiceNo/edit/': typeof AdminPreviewTransactionPreviewInvoiceNoEditIndexRoute
  '/admin/_protected/products/main/add/': typeof AdminProtectedProductsMainAddIndexRoute
  '/admin/_protected/products/main/set-price-limit/': typeof AdminProtectedProductsMainSetPriceLimitIndexRoute
  '/admin/_protected/products/provider/add/': typeof AdminProtectedProductsProviderAddIndexRoute
  '/admin/_protected/products/provider/set-profit-margin/': typeof AdminProtectedProductsProviderSetProfitMarginIndexRoute
  '/admin/_protected/transactions/automatic/$invoiceNo/edit/': typeof AdminProtectedTransactionsAutomaticInvoiceNoEditIndexRoute
  '/admin/_protected/transactions/manual/$invoiceNo/edit/': typeof AdminProtectedTransactionsManualInvoiceNoEditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/error-preview'
    | '/admin/categories-preview'
    | '/admin/products-preview'
    | '/admin/categories'
    | '/admin/content'
    | '/admin/products'
    | '/admin/transactions'
    | '/login/'
    | '/two-factor-setup/'
    | '/admin/categories-preview/'
    | '/admin/dashboard-preview/'
    | '/admin/finance-preview/'
    | '/admin/integration-preview/'
    | '/admin/products-preview/'
    | '/admin/refunds-preview/'
    | '/admin/transaction-preview/'
    | '/admin/activity/'
    | '/admin/categories/'
    | '/admin/content/'
    | '/admin/dashboard/'
    | '/admin/feedback/'
    | '/admin/financial/'
    | '/admin/flash-sales/'
    | '/admin/integration/'
    | '/admin/memberships/'
    | '/admin/notifications/'
    | '/admin/payments/'
    | '/admin/pricing/'
    | '/admin/products/'
    | '/admin/promos/'
    | '/admin/refunds/'
    | '/admin/reports/'
    | '/admin/settings/'
    | '/admin/transactions/'
    | '/admin/users/'
    | '/admin/categories-preview/category-provider/'
    | '/admin/categories-preview/category-server/'
    | '/admin/categories-preview/category-type/'
    | '/admin/categories-preview/category/'
    | '/admin/categories-preview/sub-category/'
    | '/admin/products-preview/main/'
    | '/admin/products-preview/price-log/'
    | '/admin/products-preview/provider/'
    | '/admin/categories/category-provider/'
    | '/admin/categories/category-server/'
    | '/admin/categories/category-type/'
    | '/admin/categories/category/'
    | '/admin/categories/sub-category/'
    | '/admin/content/announcements/'
    | '/admin/content/articles/'
    | '/admin/content/banners/'
    | '/admin/content/categories/'
    | '/admin/content/faqs/'
    | '/admin/content/news/'
    | '/admin/content/pages/'
    | '/admin/content/testimonials/'
    | '/admin/products/main/'
    | '/admin/products/price-log/'
    | '/admin/products/provider/'
    | '/admin/settings/security/'
    | '/admin/transactions/automatic/'
    | '/admin/transactions/manual/'
    | '/admin/users/$userId/'
    | '/admin/products-preview/main/add/'
    | '/admin/transaction-preview/$invoiceNo/edit/'
    | '/admin/products/main/add/'
    | '/admin/products/main/set-price-limit/'
    | '/admin/products/provider/add/'
    | '/admin/products/provider/set-profit-margin/'
    | '/admin/transactions/automatic/$invoiceNo/edit/'
    | '/admin/transactions/manual/$invoiceNo/edit/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin/error-preview'
    | '/login'
    | '/two-factor-setup'
    | '/admin/categories-preview'
    | '/admin/dashboard-preview'
    | '/admin/finance-preview'
    | '/admin/integration-preview'
    | '/admin/products-preview'
    | '/admin/refunds-preview'
    | '/admin/transaction-preview'
    | '/admin/activity'
    | '/admin/categories'
    | '/admin/content'
    | '/admin/dashboard'
    | '/admin/feedback'
    | '/admin/financial'
    | '/admin/flash-sales'
    | '/admin/integration'
    | '/admin/memberships'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/pricing'
    | '/admin/products'
    | '/admin/promos'
    | '/admin/refunds'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/transactions'
    | '/admin/users'
    | '/admin/categories-preview/category-provider'
    | '/admin/categories-preview/category-server'
    | '/admin/categories-preview/category-type'
    | '/admin/categories-preview/category'
    | '/admin/categories-preview/sub-category'
    | '/admin/products-preview/main'
    | '/admin/products-preview/price-log'
    | '/admin/products-preview/provider'
    | '/admin/categories/category-provider'
    | '/admin/categories/category-server'
    | '/admin/categories/category-type'
    | '/admin/categories/category'
    | '/admin/categories/sub-category'
    | '/admin/content/announcements'
    | '/admin/content/articles'
    | '/admin/content/banners'
    | '/admin/content/categories'
    | '/admin/content/faqs'
    | '/admin/content/news'
    | '/admin/content/pages'
    | '/admin/content/testimonials'
    | '/admin/products/main'
    | '/admin/products/price-log'
    | '/admin/products/provider'
    | '/admin/settings/security'
    | '/admin/transactions/automatic'
    | '/admin/transactions/manual'
    | '/admin/users/$userId'
    | '/admin/products-preview/main/add'
    | '/admin/transaction-preview/$invoiceNo/edit'
    | '/admin/products/main/add'
    | '/admin/products/main/set-price-limit'
    | '/admin/products/provider/add'
    | '/admin/products/provider/set-profit-margin'
    | '/admin/transactions/automatic/$invoiceNo/edit'
    | '/admin/transactions/manual/$invoiceNo/edit'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_enrolment'
    | '/admin/_preview'
    | '/admin/_protected'
    | '/admin/error-preview'
    | '/admin/_preview/categories-preview'
    | '/admin/_preview/products-preview'
    | '/admin/_protected/categories'
    | '/admin/_protected/content'
    | '/admin/_protected/products'
    | '/admin/_protected/transactions'
    | '/_auth/login/'
    | '/_enrolment/two-factor-setup/'
    | '/admin/_preview/categories-preview/'
    | '/admin/_preview/dashboard-preview/'
    | '/admin/_preview/finance-preview/'
    | '/admin/_preview/integration-preview/'
    | '/admin/_preview/products-preview/'
    | '/admin/_preview/refunds-preview/'
    | '/admin/_preview/transaction-preview/'
    | '/admin/_protected/activity/'
    | '/admin/_protected/categories/'
    | '/admin/_protected/content/'
    | '/admin/_protected/dashboard/'
    | '/admin/_protected/feedback/'
    | '/admin/_protected/financial/'
    | '/admin/_protected/flash-sales/'
    | '/admin/_protected/integration/'
    | '/admin/_protected/memberships/'
    | '/admin/_protected/notifications/'
    | '/admin/_protected/payments/'
    | '/admin/_protected/pricing/'
    | '/admin/_protected/products/'
    | '/admin/_protected/promos/'
    | '/admin/_protected/refunds/'
    | '/admin/_protected/reports/'
    | '/admin/_protected/settings/'
    | '/admin/_protected/transactions/'
    | '/admin/_protected/users/'
    | '/admin/_preview/categories-preview/category-provider/'
    | '/admin/_preview/categories-preview/category-server/'
    | '/admin/_preview/categories-preview/category-type/'
    | '/admin/_preview/categories-preview/category/'
    | '/admin/_preview/categories-preview/sub-category/'
    | '/admin/_preview/products-preview/main/'
    | '/admin/_preview/products-preview/price-log/'
    | '/admin/_preview/products-preview/provider/'
    | '/admin/_protected/categories/category-provider/'
    | '/admin/_protected/categories/category-server/'
    | '/admin/_protected/categories/category-type/'
    | '/admin/_protected/categories/category/'
    | '/admin/_protected/categories/sub-category/'
    | '/admin/_protected/content/announcements/'
    | '/admin/_protected/content/articles/'
    | '/admin/_protected/content/banners/'
    | '/admin/_protected/content/categories/'
    | '/admin/_protected/content/faqs/'
    | '/admin/_protected/content/news/'
    | '/admin/_protected/content/pages/'
    | '/admin/_protected/content/testimonials/'
    | '/admin/_protected/products/main/'
    | '/admin/_protected/products/price-log/'
    | '/admin/_protected/products/provider/'
    | '/admin/_protected/settings/security/'
    | '/admin/_protected/transactions/automatic/'
    | '/admin/_protected/transactions/manual/'
    | '/admin/_protected/users/$userId/'
    | '/admin/_preview/products-preview/main/add/'
    | '/admin/_preview/transaction-preview/$invoiceNo/edit/'
    | '/admin/_protected/products/main/add/'
    | '/admin/_protected/products/main/set-price-limit/'
    | '/admin/_protected/products/provider/add/'
    | '/admin/_protected/products/provider/set-profit-margin/'
    | '/admin/_protected/transactions/automatic/$invoiceNo/edit/'
    | '/admin/_protected/transactions/manual/$invoiceNo/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  EnrolmentRoute: typeof EnrolmentRouteWithChildren
  AdminPreviewRoute: typeof AdminPreviewRouteWithChildren
  AdminProtectedRoute: typeof AdminProtectedRouteWithChildren
  AdminErrorPreviewRoute: typeof AdminErrorPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_enrolment': {
      id: '/_enrolment'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof EnrolmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/error-preview': {
      id: '/admin/error-preview'
      path: '/admin/error-preview'
      fullPath: '/admin/error-preview'
      preLoaderRoute: typeof AdminErrorPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_protected': {
      id: '/admin/_protected'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_preview': {
      id: '/admin/_preview'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_enrolment/two-factor-setup/': {
      id: '/_enrolment/two-factor-setup/'
      path: '/two-factor-setup'
      fullPath: '/two-factor-setup/'
      preLoaderRoute: typeof EnrolmentTwoFactorSetupIndexRouteImport
      parentRoute: typeof EnrolmentRoute
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/admin/_protected/transactions': {
      id: '/admin/_protected/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminProtectedTransactionsRouteRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
    '/admin/_protected/products': {
      id: '/admin/_protected/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProtectedProductsRouteRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
    '/admin/_protected/content': {
      id: '/admin/_protected/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminProtectedContentRouteRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
    '/admin/_protected/categories': {
      id: '/admin/_protected/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminProtectedCategoriesRouteRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
    '/admin/_preview/products-preview': {
      id: '/admin/_preview/products-preview'
      path: '/products-preview'
      fullPath: '/admin/products-preview'
      preLoaderRoute: typeof AdminPreviewProductsPreviewRouteRouteImport
      parentRoute: typeof AdminPreviewRoute
    }
    '/admin/_preview/categories-preview': {
      id: '/admin/_preview/categories-preview'
      path: '/categories-preview'
      fullPath: '/admin/categories-preview'
      preLoaderRoute: typeof AdminPreviewCategoriesPreviewRouteRouteImport
      parentRoute: typeof AdminPreviewRoute
    }
    '/admin/_protected/users/': {
      id: '/admin/_protected/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminProtectedUsersIndexRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
    '/admin/_protected/transactions/': {
      id: '/admin/_protected/transactions/'
      path: '/'
      fullPath: '/admin/transactions/'
      preLoaderRoute: typeof AdminProtectedTransactionsIndexRouteImport
      parentRoute: typeof AdminProtectedTransactionsRouteRoute
    }
    '/admin/_protected/settings/': {
      id: '/admin/_protected/settings/'
      path: '/settings'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AdminProtectedSettingsIndexRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
    '/admin/_protected/reports/': {
      id: '/admin/_protected/reports/'
      path: '/reports'
      fullPath: '/admin/reports/'
      preLoaderRoute: typeof AdminProtectedReportsIndexRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
    '/admin/_protected/refunds/': {
      id: '/admin/_protected/refunds/'
      path: '/refunds'
      fullPath: '/admin/refunds/'
      preLoaderRoute: typeof AdminProtectedRefundsIndexRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
    '/admin/_protected/promos/': {
      id: '/admin/_protected/promos/'
      path: '/promos'
      fullPath: '/admin/promos/'
      preLoaderRoute: typeof AdminProtectedPromosIndexRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
    '/admin/_protected/products/': {
      id: '/admin/_protected/products/'
      path: '/'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminProtectedProductsIndexRouteImport
      parentRoute: typeof AdminProtectedProductsRouteRoute
    }
    '/admin/_protected/pricing/': {
      id: '/admin/_protected/pricing/'
      path: '/pricing'
      fullPath: '/admin/pricing/'
      preLoaderRoute: typeof AdminProtectedPricingIndexRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
    '/admin/_protected/payments/': {
      id: '/admin/_protected/payments/'
      path: '/payments'
      fullPath: '/admin/payments/'
      preLoaderRoute: typeof AdminProtectedPaymentsIndexRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
    '/admin/_protected/notifications/': {
      id: '/admin/_protected/notifications/'
      path: '/notifications'
      fullPath: '/admin/notifications/'
      preLoaderRoute: typeof AdminProtectedNotificationsIndexRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
    '/admin/_protected/memberships/': {
      id: '/admin/_protected/memberships/'
      path: '/memberships'
      fullPath: '/admin/memberships/'
      preLoaderRoute: typeof AdminProtectedMembershipsIndexRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
    '/admin/_protected/integration/': {
      id: '/admin/_protected/integration/'
      path: '/integration'
      fullPath: '/admin/integration/'
      preLoaderRoute: typeof AdminProtectedIntegrationIndexRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
    '/admin/_protected/flash-sales/': {
      id: '/admin/_protected/flash-sales/'
      path: '/flash-sales'
      fullPath: '/admin/flash-sales/'
      preLoaderRoute: typeof AdminProtectedFlashSalesIndexRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
    '/admin/_protected/financial/': {
      id: '/admin/_protected/financial/'
      path: '/financial'
      fullPath: '/admin/financial/'
      preLoaderRoute: typeof AdminProtectedFinancialIndexRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
    '/admin/_protected/feedback/': {
      id: '/admin/_protected/feedback/'
      path: '/feedback'
      fullPath: '/admin/feedback/'
      preLoaderRoute: typeof AdminProtectedFeedbackIndexRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
    '/admin/_protected/dashboard/': {
      id: '/admin/_protected/dashboard/'
      path: '/dashboard'
      fullPath: '/admin/dashboard/'
      preLoaderRoute: typeof AdminProtectedDashboardIndexRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
    '/admin/_protected/content/': {
      id: '/admin/_protected/content/'
      path: '/'
      fullPath: '/admin/content/'
      preLoaderRoute: typeof AdminProtectedContentIndexRouteImport
      parentRoute: typeof AdminProtectedContentRouteRoute
    }
    '/admin/_protected/categories/': {
      id: '/admin/_protected/categories/'
      path: '/'
      fullPath: '/admin/categories/'
      preLoaderRoute: typeof AdminProtectedCategoriesIndexRouteImport
      parentRoute: typeof AdminProtectedCategoriesRouteRoute
    }
    '/admin/_protected/activity/': {
      id: '/admin/_protected/activity/'
      path: '/activity'
      fullPath: '/admin/activity/'
      preLoaderRoute: typeof AdminProtectedActivityIndexRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
    '/admin/_preview/transaction-preview/': {
      id: '/admin/_preview/transaction-preview/'
      path: '/transaction-preview'
      fullPath: '/admin/transaction-preview/'
      preLoaderRoute: typeof AdminPreviewTransactionPreviewIndexRouteImport
      parentRoute: typeof AdminPreviewRoute
    }
    '/admin/_preview/refunds-preview/': {
      id: '/admin/_preview/refunds-preview/'
      path: '/refunds-preview'
      fullPath: '/admin/refunds-preview/'
      preLoaderRoute: typeof AdminPreviewRefundsPreviewIndexRouteImport
      parentRoute: typeof AdminPreviewRoute
    }
    '/admin/_preview/products-preview/': {
      id: '/admin/_preview/products-preview/'
      path: '/'
      fullPath: '/admin/products-preview/'
      preLoaderRoute: typeof AdminPreviewProductsPreviewIndexRouteImport
      parentRoute: typeof AdminPreviewProductsPreviewRouteRoute
    }
    '/admin/_preview/integration-preview/': {
      id: '/admin/_preview/integration-preview/'
      path: '/integration-preview'
      fullPath: '/admin/integration-preview/'
      preLoaderRoute: typeof AdminPreviewIntegrationPreviewIndexRouteImport
      parentRoute: typeof AdminPreviewRoute
    }
    '/admin/_preview/finance-preview/': {
      id: '/admin/_preview/finance-preview/'
      path: '/finance-preview'
      fullPath: '/admin/finance-preview/'
      preLoaderRoute: typeof AdminPreviewFinancePreviewIndexRouteImport
      parentRoute: typeof AdminPreviewRoute
    }
    '/admin/_preview/dashboard-preview/': {
      id: '/admin/_preview/dashboard-preview/'
      path: '/dashboard-preview'
      fullPath: '/admin/dashboard-preview/'
      preLoaderRoute: typeof AdminPreviewDashboardPreviewIndexRouteImport
      parentRoute: typeof AdminPreviewRoute
    }
    '/admin/_preview/categories-preview/': {
      id: '/admin/_preview/categories-preview/'
      path: '/'
      fullPath: '/admin/categories-preview/'
      preLoaderRoute: typeof AdminPreviewCategoriesPreviewIndexRouteImport
      parentRoute: typeof AdminPreviewCategoriesPreviewRouteRoute
    }
    '/admin/_protected/users/$userId/': {
      id: '/admin/_protected/users/$userId/'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId/'
      preLoaderRoute: typeof AdminProtectedUsersUserIdIndexRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
    '/admin/_protected/transactions/manual/': {
      id: '/admin/_protected/transactions/manual/'
      path: '/manual'
      fullPath: '/admin/transactions/manual/'
      preLoaderRoute: typeof AdminProtectedTransactionsManualIndexRouteImport
      parentRoute: typeof AdminProtectedTransactionsRouteRoute
    }
    '/admin/_protected/transactions/automatic/': {
      id: '/admin/_protected/transactions/automatic/'
      path: '/automatic'
      fullPath: '/admin/transactions/automatic/'
      preLoaderRoute: typeof AdminProtectedTransactionsAutomaticIndexRouteImport
      parentRoute: typeof AdminProtectedTransactionsRouteRoute
    }
    '/admin/_protected/settings/security/': {
      id: '/admin/_protected/settings/security/'
      path: '/settings/security'
      fullPath: '/admin/settings/security/'
      preLoaderRoute: typeof AdminProtectedSettingsSecurityIndexRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
    '/admin/_protected/products/provider/': {
      id: '/admin/_protected/products/provider/'
      path: '/provider'
      fullPath: '/admin/products/provider/'
      preLoaderRoute: typeof AdminProtectedProductsProviderIndexRouteImport
      parentRoute: typeof AdminProtectedProductsRouteRoute
    }
    '/admin/_protected/products/price-log/': {
      id: '/admin/_protected/products/price-log/'
      path: '/price-log'
      fullPath: '/admin/products/price-log/'
      preLoaderRoute: typeof AdminProtectedProductsPriceLogIndexRouteImport
      parentRoute: typeof AdminProtectedProductsRouteRoute
    }
    '/admin/_protected/products/main/': {
      id: '/admin/_protected/products/main/'
      path: '/main'
      fullPath: '/admin/products/main/'
      preLoaderRoute: typeof AdminProtectedProductsMainIndexRouteImport
      parentRoute: typeof AdminProtectedProductsRouteRoute
    }
    '/admin/_protected/content/testimonials/': {
      id: '/admin/_protected/content/testimonials/'
      path: '/testimonials'
      fullPath: '/admin/content/testimonials/'
      preLoaderRoute: typeof AdminProtectedContentTestimonialsIndexRouteImport
      parentRoute: typeof AdminProtectedContentRouteRoute
    }
    '/admin/_protected/content/pages/': {
      id: '/admin/_protected/content/pages/'
      path: '/pages'
      fullPath: '/admin/content/pages/'
      preLoaderRoute: typeof AdminProtectedContentPagesIndexRouteImport
      parentRoute: typeof AdminProtectedContentRouteRoute
    }
    '/admin/_protected/content/news/': {
      id: '/admin/_protected/content/news/'
      path: '/news'
      fullPath: '/admin/content/news/'
      preLoaderRoute: typeof AdminProtectedContentNewsIndexRouteImport
      parentRoute: typeof AdminProtectedContentRouteRoute
    }
    '/admin/_protected/content/faqs/': {
      id: '/admin/_protected/content/faqs/'
      path: '/faqs'
      fullPath: '/admin/content/faqs/'
      preLoaderRoute: typeof AdminProtectedContentFaqsIndexRouteImport
      parentRoute: typeof AdminProtectedContentRouteRoute
    }
    '/admin/_protected/content/categories/': {
      id: '/admin/_protected/content/categories/'
      path: '/categories'
      fullPath: '/admin/content/categories/'
      preLoaderRoute: typeof AdminProtectedContentCategoriesIndexRouteImport
      parentRoute: typeof AdminProtectedContentRouteRoute
    }
    '/admin/_protected/content/banners/': {
      id: '/admin/_protected/content/banners/'
      path: '/banners'
      fullPath: '/admin/content/banners/'
      preLoaderRoute: typeof AdminProtectedContentBannersIndexRouteImport
      parentRoute: typeof AdminProtectedContentRouteRoute
    }
    '/admin/_protected/content/articles/': {
      id: '/admin/_protected/content/articles/'
      path: '/articles'
      fullPath: '/admin/content/articles/'
      preLoaderRoute: typeof AdminProtectedContentArticlesIndexRouteImport
      parentRoute: typeof AdminProtectedContentRouteRoute
    }
    '/admin/_protected/content/announcements/': {
      id: '/admin/_protected/content/announcements/'
      path: '/announcements'
      fullPath: '/admin/content/announcements/'
      preLoaderRoute: typeof AdminProtectedContentAnnouncementsIndexRouteImport
      parentRoute: typeof AdminProtectedContentRouteRoute
    }
    '/admin/_protected/categories/sub-category/': {
      id: '/admin/_protected/categories/sub-category/'
      path: '/sub-category'
      fullPath: '/admin/categories/sub-category/'
      preLoaderRoute: typeof AdminProtectedCategoriesSubCategoryIndexRouteImport
      parentRoute: typeof AdminProtectedCategoriesRouteRoute
    }
    '/admin/_protected/categories/category/': {
      id: '/admin/_protected/categories/category/'
      path: '/category'
      fullPath: '/admin/categories/category/'
      preLoaderRoute: typeof AdminProtectedCategoriesCategoryIndexRouteImport
      parentRoute: typeof AdminProtectedCategoriesRouteRoute
    }
    '/admin/_protected/categories/category-type/': {
      id: '/admin/_protected/categories/category-type/'
      path: '/category-type'
      fullPath: '/admin/categories/category-type/'
      preLoaderRoute: typeof AdminProtectedCategoriesCategoryTypeIndexRouteImport
      parentRoute: typeof AdminProtectedCategoriesRouteRoute
    }
    '/admin/_protected/categories/category-server/': {
      id: '/admin/_protected/categories/category-server/'
      path: '/category-server'
      fullPath: '/admin/categories/category-server/'
      preLoaderRoute: typeof AdminProtectedCategoriesCategoryServerIndexRouteImport
      parentRoute: typeof AdminProtectedCategoriesRouteRoute
    }
    '/admin/_protected/categories/category-provider/': {
      id: '/admin/_protected/categories/category-provider/'
      path: '/category-provider'
      fullPath: '/admin/categories/category-provider/'
      preLoaderRoute: typeof AdminProtectedCategoriesCategoryProviderIndexRouteImport
      parentRoute: typeof AdminProtectedCategoriesRouteRoute
    }
    '/admin/_preview/products-preview/provider/': {
      id: '/admin/_preview/products-preview/provider/'
      path: '/provider'
      fullPath: '/admin/products-preview/provider/'
      preLoaderRoute: typeof AdminPreviewProductsPreviewProviderIndexRouteImport
      parentRoute: typeof AdminPreviewProductsPreviewRouteRoute
    }
    '/admin/_preview/products-preview/price-log/': {
      id: '/admin/_preview/products-preview/price-log/'
      path: '/price-log'
      fullPath: '/admin/products-preview/price-log/'
      preLoaderRoute: typeof AdminPreviewProductsPreviewPriceLogIndexRouteImport
      parentRoute: typeof AdminPreviewProductsPreviewRouteRoute
    }
    '/admin/_preview/products-preview/main/': {
      id: '/admin/_preview/products-preview/main/'
      path: '/main'
      fullPath: '/admin/products-preview/main/'
      preLoaderRoute: typeof AdminPreviewProductsPreviewMainIndexRouteImport
      parentRoute: typeof AdminPreviewProductsPreviewRouteRoute
    }
    '/admin/_preview/categories-preview/sub-category/': {
      id: '/admin/_preview/categories-preview/sub-category/'
      path: '/sub-category'
      fullPath: '/admin/categories-preview/sub-category/'
      preLoaderRoute: typeof AdminPreviewCategoriesPreviewSubCategoryIndexRouteImport
      parentRoute: typeof AdminPreviewCategoriesPreviewRouteRoute
    }
    '/admin/_preview/categories-preview/category/': {
      id: '/admin/_preview/categories-preview/category/'
      path: '/category'
      fullPath: '/admin/categories-preview/category/'
      preLoaderRoute: typeof AdminPreviewCategoriesPreviewCategoryIndexRouteImport
      parentRoute: typeof AdminPreviewCategoriesPreviewRouteRoute
    }
    '/admin/_preview/categories-preview/category-type/': {
      id: '/admin/_preview/categories-preview/category-type/'
      path: '/category-type'
      fullPath: '/admin/categories-preview/category-type/'
      preLoaderRoute: typeof AdminPreviewCategoriesPreviewCategoryTypeIndexRouteImport
      parentRoute: typeof AdminPreviewCategoriesPreviewRouteRoute
    }
    '/admin/_preview/categories-preview/category-server/': {
      id: '/admin/_preview/categories-preview/category-server/'
      path: '/category-server'
      fullPath: '/admin/categories-preview/category-server/'
      preLoaderRoute: typeof AdminPreviewCategoriesPreviewCategoryServerIndexRouteImport
      parentRoute: typeof AdminPreviewCategoriesPreviewRouteRoute
    }
    '/admin/_preview/categories-preview/category-provider/': {
      id: '/admin/_preview/categories-preview/category-provider/'
      path: '/category-provider'
      fullPath: '/admin/categories-preview/category-provider/'
      preLoaderRoute: typeof AdminPreviewCategoriesPreviewCategoryProviderIndexRouteImport
      parentRoute: typeof AdminPreviewCategoriesPreviewRouteRoute
    }
    '/admin/_protected/products/provider/set-profit-margin/': {
      id: '/admin/_protected/products/provider/set-profit-margin/'
      path: '/provider/set-profit-margin'
      fullPath: '/admin/products/provider/set-profit-margin/'
      preLoaderRoute: typeof AdminProtectedProductsProviderSetProfitMarginIndexRouteImport
      parentRoute: typeof AdminProtectedProductsRouteRoute
    }
    '/admin/_protected/products/provider/add/': {
      id: '/admin/_protected/products/provider/add/'
      path: '/provider/add'
      fullPath: '/admin/products/provider/add/'
      preLoaderRoute: typeof AdminProtectedProductsProviderAddIndexRouteImport
      parentRoute: typeof AdminProtectedProductsRouteRoute
    }
    '/admin/_protected/products/main/set-price-limit/': {
      id: '/admin/_protected/products/main/set-price-limit/'
      path: '/main/set-price-limit'
      fullPath: '/admin/products/main/set-price-limit/'
      preLoaderRoute: typeof AdminProtectedProductsMainSetPriceLimitIndexRouteImport
      parentRoute: typeof AdminProtectedProductsRouteRoute
    }
    '/admin/_protected/products/main/add/': {
      id: '/admin/_protected/products/main/add/'
      path: '/main/add'
      fullPath: '/admin/products/main/add/'
      preLoaderRoute: typeof AdminProtectedProductsMainAddIndexRouteImport
      parentRoute: typeof AdminProtectedProductsRouteRoute
    }
    '/admin/_preview/transaction-preview/$invoiceNo/edit/': {
      id: '/admin/_preview/transaction-preview/$invoiceNo/edit/'
      path: '/transaction-preview/$invoiceNo/edit'
      fullPath: '/admin/transaction-preview/$invoiceNo/edit/'
      preLoaderRoute: typeof AdminPreviewTransactionPreviewInvoiceNoEditIndexRouteImport
      parentRoute: typeof AdminPreviewRoute
    }
    '/admin/_preview/products-preview/main/add/': {
      id: '/admin/_preview/products-preview/main/add/'
      path: '/main/add'
      fullPath: '/admin/products-preview/main/add/'
      preLoaderRoute: typeof AdminPreviewProductsPreviewMainAddIndexRouteImport
      parentRoute: typeof AdminPreviewProductsPreviewRouteRoute
    }
    '/admin/_protected/transactions/manual/$invoiceNo/edit/': {
      id: '/admin/_protected/transactions/manual/$invoiceNo/edit/'
      path: '/manual/$invoiceNo/edit'
      fullPath: '/admin/transactions/manual/$invoiceNo/edit/'
      preLoaderRoute: typeof AdminProtectedTransactionsManualInvoiceNoEditIndexRouteImport
      parentRoute: typeof AdminProtectedTransactionsRouteRoute
    }
    '/admin/_protected/transactions/automatic/$invoiceNo/edit/': {
      id: '/admin/_protected/transactions/automatic/$invoiceNo/edit/'
      path: '/automatic/$invoiceNo/edit'
      fullPath: '/admin/transactions/automatic/$invoiceNo/edit/'
      preLoaderRoute: typeof AdminProtectedTransactionsAutomaticInvoiceNoEditIndexRouteImport
      parentRoute: typeof AdminProtectedTransactionsRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginIndexRoute: AuthLoginIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface EnrolmentRouteChildren {
  EnrolmentTwoFactorSetupIndexRoute: typeof EnrolmentTwoFactorSetupIndexRoute
}

const EnrolmentRouteChildren: EnrolmentRouteChildren = {
  EnrolmentTwoFactorSetupIndexRoute: EnrolmentTwoFactorSetupIndexRoute,
}

const EnrolmentRouteWithChildren = EnrolmentRoute._addFileChildren(
  EnrolmentRouteChildren,
)

interface AdminPreviewCategoriesPreviewRouteRouteChildren {
  AdminPreviewCategoriesPreviewIndexRoute: typeof AdminPreviewCategoriesPreviewIndexRoute
  AdminPreviewCategoriesPreviewCategoryProviderIndexRoute: typeof AdminPreviewCategoriesPreviewCategoryProviderIndexRoute
  AdminPreviewCategoriesPreviewCategoryServerIndexRoute: typeof AdminPreviewCategoriesPreviewCategoryServerIndexRoute
  AdminPreviewCategoriesPreviewCategoryTypeIndexRoute: typeof AdminPreviewCategoriesPreviewCategoryTypeIndexRoute
  AdminPreviewCategoriesPreviewCategoryIndexRoute: typeof AdminPreviewCategoriesPreviewCategoryIndexRoute
  AdminPreviewCategoriesPreviewSubCategoryIndexRoute: typeof AdminPreviewCategoriesPreviewSubCategoryIndexRoute
}

const AdminPreviewCategoriesPreviewRouteRouteChildren: AdminPreviewCategoriesPreviewRouteRouteChildren =
  {
    AdminPreviewCategoriesPreviewIndexRoute:
      AdminPreviewCategoriesPreviewIndexRoute,
    AdminPreviewCategoriesPreviewCategoryProviderIndexRoute:
      AdminPreviewCategoriesPreviewCategoryProviderIndexRoute,
    AdminPreviewCategoriesPreviewCategoryServerIndexRoute:
      AdminPreviewCategoriesPreviewCategoryServerIndexRoute,
    AdminPreviewCategoriesPreviewCategoryTypeIndexRoute:
      AdminPreviewCategoriesPreviewCategoryTypeIndexRoute,
    AdminPreviewCategoriesPreviewCategoryIndexRoute:
      AdminPreviewCategoriesPreviewCategoryIndexRoute,
    AdminPreviewCategoriesPreviewSubCategoryIndexRoute:
      AdminPreviewCategoriesPreviewSubCategoryIndexRoute,
  }

const AdminPreviewCategoriesPreviewRouteRouteWithChildren =
  AdminPreviewCategoriesPreviewRouteRoute._addFileChildren(
    AdminPreviewCategoriesPreviewRouteRouteChildren,
  )

interface AdminPreviewProductsPreviewRouteRouteChildren {
  AdminPreviewProductsPreviewIndexRoute: typeof AdminPreviewProductsPreviewIndexRoute
  AdminPreviewProductsPreviewMainIndexRoute: typeof AdminPreviewProductsPreviewMainIndexRoute
  AdminPreviewProductsPreviewPriceLogIndexRoute: typeof AdminPreviewProductsPreviewPriceLogIndexRoute
  AdminPreviewProductsPreviewProviderIndexRoute: typeof AdminPreviewProductsPreviewProviderIndexRoute
  AdminPreviewProductsPreviewMainAddIndexRoute: typeof AdminPreviewProductsPreviewMainAddIndexRoute
}

const AdminPreviewProductsPreviewRouteRouteChildren: AdminPreviewProductsPreviewRouteRouteChildren =
  {
    AdminPreviewProductsPreviewIndexRoute:
      AdminPreviewProductsPreviewIndexRoute,
    AdminPreviewProductsPreviewMainIndexRoute:
      AdminPreviewProductsPreviewMainIndexRoute,
    AdminPreviewProductsPreviewPriceLogIndexRoute:
      AdminPreviewProductsPreviewPriceLogIndexRoute,
    AdminPreviewProductsPreviewProviderIndexRoute:
      AdminPreviewProductsPreviewProviderIndexRoute,
    AdminPreviewProductsPreviewMainAddIndexRoute:
      AdminPreviewProductsPreviewMainAddIndexRoute,
  }

const AdminPreviewProductsPreviewRouteRouteWithChildren =
  AdminPreviewProductsPreviewRouteRoute._addFileChildren(
    AdminPreviewProductsPreviewRouteRouteChildren,
  )

interface AdminPreviewRouteChildren {
  AdminPreviewCategoriesPreviewRouteRoute: typeof AdminPreviewCategoriesPreviewRouteRouteWithChildren
  AdminPreviewProductsPreviewRouteRoute: typeof AdminPreviewProductsPreviewRouteRouteWithChildren
  AdminPreviewDashboardPreviewIndexRoute: typeof AdminPreviewDashboardPreviewIndexRoute
  AdminPreviewFinancePreviewIndexRoute: typeof AdminPreviewFinancePreviewIndexRoute
  AdminPreviewIntegrationPreviewIndexRoute: typeof AdminPreviewIntegrationPreviewIndexRoute
  AdminPreviewRefundsPreviewIndexRoute: typeof AdminPreviewRefundsPreviewIndexRoute
  AdminPreviewTransactionPreviewIndexRoute: typeof AdminPreviewTransactionPreviewIndexRoute
  AdminPreviewTransactionPreviewInvoiceNoEditIndexRoute: typeof AdminPreviewTransactionPreviewInvoiceNoEditIndexRoute
}

const AdminPreviewRouteChildren: AdminPreviewRouteChildren = {
  AdminPreviewCategoriesPreviewRouteRoute:
    AdminPreviewCategoriesPreviewRouteRouteWithChildren,
  AdminPreviewProductsPreviewRouteRoute:
    AdminPreviewProductsPreviewRouteRouteWithChildren,
  AdminPreviewDashboardPreviewIndexRoute:
    AdminPreviewDashboardPreviewIndexRoute,
  AdminPreviewFinancePreviewIndexRoute: AdminPreviewFinancePreviewIndexRoute,
  AdminPreviewIntegrationPreviewIndexRoute:
    AdminPreviewIntegrationPreviewIndexRoute,
  AdminPreviewRefundsPreviewIndexRoute: AdminPreviewRefundsPreviewIndexRoute,
  AdminPreviewTransactionPreviewIndexRoute:
    AdminPreviewTransactionPreviewIndexRoute,
  AdminPreviewTransactionPreviewInvoiceNoEditIndexRoute:
    AdminPreviewTransactionPreviewInvoiceNoEditIndexRoute,
}

const AdminPreviewRouteWithChildren = AdminPreviewRoute._addFileChildren(
  AdminPreviewRouteChildren,
)

interface AdminProtectedCategoriesRouteRouteChildren {
  AdminProtectedCategoriesIndexRoute: typeof AdminProtectedCategoriesIndexRoute
  AdminProtectedCategoriesCategoryProviderIndexRoute: typeof AdminProtectedCategoriesCategoryProviderIndexRoute
  AdminProtectedCategoriesCategoryServerIndexRoute: typeof AdminProtectedCategoriesCategoryServerIndexRoute
  AdminProtectedCategoriesCategoryTypeIndexRoute: typeof AdminProtectedCategoriesCategoryTypeIndexRoute
  AdminProtectedCategoriesCategoryIndexRoute: typeof AdminProtectedCategoriesCategoryIndexRoute
  AdminProtectedCategoriesSubCategoryIndexRoute: typeof AdminProtectedCategoriesSubCategoryIndexRoute
}

const AdminProtectedCategoriesRouteRouteChildren: AdminProtectedCategoriesRouteRouteChildren =
  {
    AdminProtectedCategoriesIndexRoute: AdminProtectedCategoriesIndexRoute,
    AdminProtectedCategoriesCategoryProviderIndexRoute:
      AdminProtectedCategoriesCategoryProviderIndexRoute,
    AdminProtectedCategoriesCategoryServerIndexRoute:
      AdminProtectedCategoriesCategoryServerIndexRoute,
    AdminProtectedCategoriesCategoryTypeIndexRoute:
      AdminProtectedCategoriesCategoryTypeIndexRoute,
    AdminProtectedCategoriesCategoryIndexRoute:
      AdminProtectedCategoriesCategoryIndexRoute,
    AdminProtectedCategoriesSubCategoryIndexRoute:
      AdminProtectedCategoriesSubCategoryIndexRoute,
  }

const AdminProtectedCategoriesRouteRouteWithChildren =
  AdminProtectedCategoriesRouteRoute._addFileChildren(
    AdminProtectedCategoriesRouteRouteChildren,
  )

interface AdminProtectedContentRouteRouteChildren {
  AdminProtectedContentIndexRoute: typeof AdminProtectedContentIndexRoute
  AdminProtectedContentAnnouncementsIndexRoute: typeof AdminProtectedContentAnnouncementsIndexRoute
  AdminProtectedContentArticlesIndexRoute: typeof AdminProtectedContentArticlesIndexRoute
  AdminProtectedContentBannersIndexRoute: typeof AdminProtectedContentBannersIndexRoute
  AdminProtectedContentCategoriesIndexRoute: typeof AdminProtectedContentCategoriesIndexRoute
  AdminProtectedContentFaqsIndexRoute: typeof AdminProtectedContentFaqsIndexRoute
  AdminProtectedContentNewsIndexRoute: typeof AdminProtectedContentNewsIndexRoute
  AdminProtectedContentPagesIndexRoute: typeof AdminProtectedContentPagesIndexRoute
  AdminProtectedContentTestimonialsIndexRoute: typeof AdminProtectedContentTestimonialsIndexRoute
}

const AdminProtectedContentRouteRouteChildren: AdminProtectedContentRouteRouteChildren =
  {
    AdminProtectedContentIndexRoute: AdminProtectedContentIndexRoute,
    AdminProtectedContentAnnouncementsIndexRoute:
      AdminProtectedContentAnnouncementsIndexRoute,
    AdminProtectedContentArticlesIndexRoute:
      AdminProtectedContentArticlesIndexRoute,
    AdminProtectedContentBannersIndexRoute:
      AdminProtectedContentBannersIndexRoute,
    AdminProtectedContentCategoriesIndexRoute:
      AdminProtectedContentCategoriesIndexRoute,
    AdminProtectedContentFaqsIndexRoute: AdminProtectedContentFaqsIndexRoute,
    AdminProtectedContentNewsIndexRoute: AdminProtectedContentNewsIndexRoute,
    AdminProtectedContentPagesIndexRoute: AdminProtectedContentPagesIndexRoute,
    AdminProtectedContentTestimonialsIndexRoute:
      AdminProtectedContentTestimonialsIndexRoute,
  }

const AdminProtectedContentRouteRouteWithChildren =
  AdminProtectedContentRouteRoute._addFileChildren(
    AdminProtectedContentRouteRouteChildren,
  )

interface AdminProtectedProductsRouteRouteChildren {
  AdminProtectedProductsIndexRoute: typeof AdminProtectedProductsIndexRoute
  AdminProtectedProductsMainIndexRoute: typeof AdminProtectedProductsMainIndexRoute
  AdminProtectedProductsPriceLogIndexRoute: typeof AdminProtectedProductsPriceLogIndexRoute
  AdminProtectedProductsProviderIndexRoute: typeof AdminProtectedProductsProviderIndexRoute
  AdminProtectedProductsMainAddIndexRoute: typeof AdminProtectedProductsMainAddIndexRoute
  AdminProtectedProductsMainSetPriceLimitIndexRoute: typeof AdminProtectedProductsMainSetPriceLimitIndexRoute
  AdminProtectedProductsProviderAddIndexRoute: typeof AdminProtectedProductsProviderAddIndexRoute
  AdminProtectedProductsProviderSetProfitMarginIndexRoute: typeof AdminProtectedProductsProviderSetProfitMarginIndexRoute
}

const AdminProtectedProductsRouteRouteChildren: AdminProtectedProductsRouteRouteChildren =
  {
    AdminProtectedProductsIndexRoute: AdminProtectedProductsIndexRoute,
    AdminProtectedProductsMainIndexRoute: AdminProtectedProductsMainIndexRoute,
    AdminProtectedProductsPriceLogIndexRoute:
      AdminProtectedProductsPriceLogIndexRoute,
    AdminProtectedProductsProviderIndexRoute:
      AdminProtectedProductsProviderIndexRoute,
    AdminProtectedProductsMainAddIndexRoute:
      AdminProtectedProductsMainAddIndexRoute,
    AdminProtectedProductsMainSetPriceLimitIndexRoute:
      AdminProtectedProductsMainSetPriceLimitIndexRoute,
    AdminProtectedProductsProviderAddIndexRoute:
      AdminProtectedProductsProviderAddIndexRoute,
    AdminProtectedProductsProviderSetProfitMarginIndexRoute:
      AdminProtectedProductsProviderSetProfitMarginIndexRoute,
  }

const AdminProtectedProductsRouteRouteWithChildren =
  AdminProtectedProductsRouteRoute._addFileChildren(
    AdminProtectedProductsRouteRouteChildren,
  )

interface AdminProtectedTransactionsRouteRouteChildren {
  AdminProtectedTransactionsIndexRoute: typeof AdminProtectedTransactionsIndexRoute
  AdminProtectedTransactionsAutomaticIndexRoute: typeof AdminProtectedTransactionsAutomaticIndexRoute
  AdminProtectedTransactionsManualIndexRoute: typeof AdminProtectedTransactionsManualIndexRoute
  AdminProtectedTransactionsAutomaticInvoiceNoEditIndexRoute: typeof AdminProtectedTransactionsAutomaticInvoiceNoEditIndexRoute
  AdminProtectedTransactionsManualInvoiceNoEditIndexRoute: typeof AdminProtectedTransactionsManualInvoiceNoEditIndexRoute
}

const AdminProtectedTransactionsRouteRouteChildren: AdminProtectedTransactionsRouteRouteChildren =
  {
    AdminProtectedTransactionsIndexRoute: AdminProtectedTransactionsIndexRoute,
    AdminProtectedTransactionsAutomaticIndexRoute:
      AdminProtectedTransactionsAutomaticIndexRoute,
    AdminProtectedTransactionsManualIndexRoute:
      AdminProtectedTransactionsManualIndexRoute,
    AdminProtectedTransactionsAutomaticInvoiceNoEditIndexRoute:
      AdminProtectedTransactionsAutomaticInvoiceNoEditIndexRoute,
    AdminProtectedTransactionsManualInvoiceNoEditIndexRoute:
      AdminProtectedTransactionsManualInvoiceNoEditIndexRoute,
  }

const AdminProtectedTransactionsRouteRouteWithChildren =
  AdminProtectedTransactionsRouteRoute._addFileChildren(
    AdminProtectedTransactionsRouteRouteChildren,
  )

interface AdminProtectedRouteChildren {
  AdminProtectedCategoriesRouteRoute: typeof AdminProtectedCategoriesRouteRouteWithChildren
  AdminProtectedContentRouteRoute: typeof AdminProtectedContentRouteRouteWithChildren
  AdminProtectedProductsRouteRoute: typeof AdminProtectedProductsRouteRouteWithChildren
  AdminProtectedTransactionsRouteRoute: typeof AdminProtectedTransactionsRouteRouteWithChildren
  AdminProtectedActivityIndexRoute: typeof AdminProtectedActivityIndexRoute
  AdminProtectedDashboardIndexRoute: typeof AdminProtectedDashboardIndexRoute
  AdminProtectedFeedbackIndexRoute: typeof AdminProtectedFeedbackIndexRoute
  AdminProtectedFinancialIndexRoute: typeof AdminProtectedFinancialIndexRoute
  AdminProtectedFlashSalesIndexRoute: typeof AdminProtectedFlashSalesIndexRoute
  AdminProtectedIntegrationIndexRoute: typeof AdminProtectedIntegrationIndexRoute
  AdminProtectedMembershipsIndexRoute: typeof AdminProtectedMembershipsIndexRoute
  AdminProtectedNotificationsIndexRoute: typeof AdminProtectedNotificationsIndexRoute
  AdminProtectedPaymentsIndexRoute: typeof AdminProtectedPaymentsIndexRoute
  AdminProtectedPricingIndexRoute: typeof AdminProtectedPricingIndexRoute
  AdminProtectedPromosIndexRoute: typeof AdminProtectedPromosIndexRoute
  AdminProtectedRefundsIndexRoute: typeof AdminProtectedRefundsIndexRoute
  AdminProtectedReportsIndexRoute: typeof AdminProtectedReportsIndexRoute
  AdminProtectedSettingsIndexRoute: typeof AdminProtectedSettingsIndexRoute
  AdminProtectedUsersIndexRoute: typeof AdminProtectedUsersIndexRoute
  AdminProtectedSettingsSecurityIndexRoute: typeof AdminProtectedSettingsSecurityIndexRoute
  AdminProtectedUsersUserIdIndexRoute: typeof AdminProtectedUsersUserIdIndexRoute
}

const AdminProtectedRouteChildren: AdminProtectedRouteChildren = {
  AdminProtectedCategoriesRouteRoute:
    AdminProtectedCategoriesRouteRouteWithChildren,
  AdminProtectedContentRouteRoute: AdminProtectedContentRouteRouteWithChildren,
  AdminProtectedProductsRouteRoute:
    AdminProtectedProductsRouteRouteWithChildren,
  AdminProtectedTransactionsRouteRoute:
    AdminProtectedTransactionsRouteRouteWithChildren,
  AdminProtectedActivityIndexRoute: AdminProtectedActivityIndexRoute,
  AdminProtectedDashboardIndexRoute: AdminProtectedDashboardIndexRoute,
  AdminProtectedFeedbackIndexRoute: AdminProtectedFeedbackIndexRoute,
  AdminProtectedFinancialIndexRoute: AdminProtectedFinancialIndexRoute,
  AdminProtectedFlashSalesIndexRoute: AdminProtectedFlashSalesIndexRoute,
  AdminProtectedIntegrationIndexRoute: AdminProtectedIntegrationIndexRoute,
  AdminProtectedMembershipsIndexRoute: AdminProtectedMembershipsIndexRoute,
  AdminProtectedNotificationsIndexRoute: AdminProtectedNotificationsIndexRoute,
  AdminProtectedPaymentsIndexRoute: AdminProtectedPaymentsIndexRoute,
  AdminProtectedPricingIndexRoute: AdminProtectedPricingIndexRoute,
  AdminProtectedPromosIndexRoute: AdminProtectedPromosIndexRoute,
  AdminProtectedRefundsIndexRoute: AdminProtectedRefundsIndexRoute,
  AdminProtectedReportsIndexRoute: AdminProtectedReportsIndexRoute,
  AdminProtectedSettingsIndexRoute: AdminProtectedSettingsIndexRoute,
  AdminProtectedUsersIndexRoute: AdminProtectedUsersIndexRoute,
  AdminProtectedSettingsSecurityIndexRoute:
    AdminProtectedSettingsSecurityIndexRoute,
  AdminProtectedUsersUserIdIndexRoute: AdminProtectedUsersUserIdIndexRoute,
}

const AdminProtectedRouteWithChildren = AdminProtectedRoute._addFileChildren(
  AdminProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  EnrolmentRoute: EnrolmentRouteWithChildren,
  AdminPreviewRoute: AdminPreviewRouteWithChildren,
  AdminProtectedRoute: AdminProtectedRouteWithChildren,
  AdminErrorPreviewRoute: AdminErrorPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
